apiVersion: platform.acme.co/v1alpha1
kind: Fleet
metadata:
  name: fleet1
spec:
  parameters:
    name: "test-fleet"
    shape:
      name: "basic-shape"
      components:
        - name: "argocd"
          type: "argocd"
          version: "v2.8.0"
        - name: "dns"
          type: "dns"
          version: "v1.10.0"
    archetype:
      name: "dual-cluster-archetype"
      clusters:
        - name: "atlas-main"
          type: "atlaskube"
          initialNodeCount: 2
          project: "test-project"
          location: "us-central1"
          networkRef:
            name: "test-network"
        - name: "autobahn-main"
          type: "autobahn"
          initialNodeCount: 1
          project: "test-project"
          location: "us-east1"
          networkRef:
            name: "test-network" 