apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcomponents.platform.acme.co
spec:
  compositeTypeRef:
    apiVersion: platform.acme.co/v1alpha1
    kind: XComponent
  mode: Pipeline
  pipeline:
    - step: compose
      functionRef:
        name: crossplane-contrib-function-kcl
      input:
        apiVersion: krm.kcl.dev/v1alpha1
        kind: KCLRun
        metadata:
          name: compose-component
        spec:
          target: Resources
          params:
            name: "input-instance"
          source: |
            oxr = option("params").oxr
            dxr = {
                **oxr
                status.dummy = "cool-status"
            }
            readyCondition = {
                    conditionStatus: "True"
                    conditionType: "Ready"
                    time: "15s"
            }
            items = [{
                apiVersion: "nop.crossplane.io/v1alpha1"
                kind: "NopResource"
                metadata.name = oxr.metadata.name
                spec.forProvider = {
                  conditionAfter = [readyCondition]
                  fields = {
                    name: oxr.spec.parameters.name
                    type: oxr.spec.parameters.type
                    version: oxr.spec.parameters.version if oxr.spec.parameters.version else "latest"
                    configuration: oxr.spec.parameters.configuration if oxr.spec.parameters.configuration else {}
                  }
                }
            }]

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready 